### PR TITLE
Round3

### PR DESCRIPTION
**Pull request by lducas**

### CODE REVIEW

**Comment by jschanck-si** [comment]
I checked the Kyber part---I don't know the details on the Dilithium side. I didn't like how slow the search for b & m was given that with STEPS_m > 1 the optimization routine was not guaranteed to find the optimal b. So I changed that part. Otherwise, looks good to me.

**Comment by lducas** [comment]
The binary search is only guaranteed to find the optimum is the function is convex. Do we know that for sure ? (on these particular instances the result is the same though). Your call.

**Comment by jschanck** [comment]
I think it's safe to assume that cost_svp(b) is weakly increasing.

**Comment by lducas** [comment]
I misread and thought the binary search was on m, not on b. Excellent.

**Pull request merged**
